In [8]:
import pandas as pd
import yaml
import csv

path_month = ['2023-10', '2023-11', '2023-12', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06','2024-07', '2024-08', '2024-09', '2024-10', '2024-11']
path_date = pd.date_range(start='2023-10-01', end='2024-11-30').strftime('%Y-%m-%d').tolist()
path_time = ['05-30-00']  # Add all possible times here

wholedf = pd.DataFrame()
for i in path_month:
    for j in path_date:
        for t in path_time:
            file_path = f'D:\\Projects\\Python NBs and Files\\MINI PROJECT_2\\{i}\\{j}_{t}.yaml'
            try:
                with open(file_path, 'r') as yaml_file:
                    yaml_data = yaml.safe_load(yaml_file)
                    if yaml_data:
                        headers = list(yaml_data[0].keys())
                        rows = [list(item.values()) for item in yaml_data]
                    else:
                        headers = []
                        rows = []
                    with open('combined_output_cs.csv', 'a', newline='') as csv_file:  # Use 'a' to append
                        writer = csv.writer(csv_file)
                        if csv_file.tell() == 0:  # Write header only once
                            writer.writerow(headers)
                        writer.writerows(rows)
            except FileNotFoundError:
                continue

In [10]:
df = pd.read_csv("D:\\Projects\\Python NBs and Files\\MINI PROJECT_2\\combined_output_cs.csv")
df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,602.95,2023-10-03 05:30:00,604.9,589.60,2023-10,596.60,15322196
1,BAJFINANCE,7967.60,2023-10-03 05:30:00,7975.5,7755.00,2023-10,7780.80,944555
2,TITAN,3196.25,2023-10-03 05:30:00,3212.5,3114.40,2023-10,3148.80,1007308
3,ITC,439.75,2023-10-03 05:30:00,442.9,439.25,2023-10,441.00,7481883
4,TCS,3513.85,2023-10-03 05:30:00,3534.2,3480.10,2023-10,3534.20,1948148
...,...,...,...,...,...,...,...,...
14195,HINDALCO,652.10,2024-11-22 05:30:00,657.3,647.40,2024-11,652.95,3586402
14196,HEROMOTOCO,4794.10,2024-11-22 05:30:00,4808.4,4742.00,2024-11,4778.40,394712
14197,AXISBANK,1142.40,2024-11-22 05:30:00,1147.9,1127.55,2024-11,1136.65,16687505
14198,HDFCBANK,1745.60,2024-11-22 05:30:00,1754.3,1729.55,2024-11,1743.55,12386806
14199,BAJAJ-AUTO,9481.65,2024-11-22 05:30:00,9602.9,9444.10,2024-11,9545.00,619823

In [11]:
df_final = df.reset_index(drop=True)
df_final

,Ticker,close,date,high,low,month,open,volume
0,SBIN,602.95,2023-10-03 05:30:00,604.9,589.60,2023-10,596.60,15322196
1,BAJFINANCE,7967.60,2023-10-03 05:30:00,7975.5,7755.00,2023-10,7780.80,944555
2,TITAN,3196.25,2023-10-03 05:30:00,3212.5,3114.40,2023-10,3148.80,1007308
3,ITC,439.75,2023-10-03 05:30:00,442.9,439.25,2023-10,441.00,7481883
4,TCS,3513.85,2023-10-03 05:30:00,3534.2,3480.10,2023-10,3534.20,1948148
...,...,...,...,...,...,...,...,...
14195,HINDALCO,652.10,2024-11-22 05:30:00,657.3,647.40,2024-11,652.95,3586402
14196,HEROMOTOCO,4794.10,2024-11-22 05:30:00,4808.4,4742.00,2024-11,4778.40,394712
14197,AXISBANK,1142.40,2024-11-22 05:30:00,1147.9,1127.55,2024-11,1136.65,16687505
14198,HDFCBANK,1745.60,2024-11-22 05:30:00,1754.3,1729.55,2024-11,1743.55,12386806
14199,BAJAJ-AUTO,9481.65,2024-11-22 05:30:00,9602.9,9444.10,2024-11,9545.00,619823

In [ ]:
df_final.to_csv("D:\\Projects\\Python NBs and Files\\MINI PROJECT_2\\Stock_Market_Full_Data.csv", index=False)

In [15]:
df = df_final
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14200 entries, 0 to 14199
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ticker  14200 non-null  object
 1   close   14200 non-null  float64
 2   date    14200 non-null  object
 3   high    14200 non-null  float64
 4   low     14200 non-null  float64
 5   month   14200 non-null  object
 6   open    14200 non-null  float64
 7   volume  14200 non-null  int64
dtypes: float64(4), int64(1), object(3)
memory usage: 887.6+ KB

In [16]:
df.sample(10)

,Ticker,close,date,high,low,month,open,volume
11338,SHRIRAMFIN,3204.50,2024-08-30 05:30:00,3224.40,3177.00,2024-08,3200.75,2205225
3894,SBILIFE,1375.50,2024-01-23 05:30:00,1448.65,1367.35,2024-01,1444.00,2880301
13688,SHRIRAMFIN,3186.70,2024-11-06 05:30:00,3200.00,3136.30,2024-11,3187.00,858932
5743,BRITANNIA,4974.20,2024-03-15 05:30:00,5008.70,4912.00,2024-03,4917.45,491571
7832,ASIANPAINT,2851.80,2024-05-21 05:30:00,2866.95,2801.00,2024-05,2815.00,921822
8060,ULTRACEMCO,10178.90,2024-05-28 05:30:00,10365.85,10146.45,2024-05,10264.00,403774
4321,M&M,1727.65,2024-02-06 05:30:00,1730.00,1706.00,2024-02,1710.95,2219874
12025,ADANIPORTS,1408.20,2024-09-19 05:30:00,1438.00,1394.45,2024-09,1433.00,2072872
7810,ULTRACEMCO,9789.40,2024-05-21 05:30:00,9850.75,9762.05,2024-05,9826.00,346947
11780,MARUTI,12400.85,2024-09-12 05:30:00,12427.00,12151.35,2024-09,12262.10,547830